# Generated by Django 3.2.7 on 2022-03-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
