# Generated by Django 3.2.7 on 2022-04-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commentCount',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='users.product'),
        ),
    ]
