# Generated by Django 3.2.7 on 2022-04-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220406_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wordcloud',
            field=models.ImageField(default='default.jpg', upload_to='wordcloud_images'),
        ),
    ]
