# Generated by Django 3.2.7 on 2022-04-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_product_wordcloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wordcloud',
            field=models.CharField(max_length=500),
        ),
    ]
