# Generated by Django 3.2.7 on 2022-05-16 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_product_wordcloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='unique Id for this table', primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=150)),
                ('catch', models.CharField(blank=True, max_length=350)),
                ('preCatch', models.CharField(blank=True, max_length=350)),
                ('subCatch', models.CharField(blank=True, max_length=350)),
                ('headLine', models.CharField(blank=True, max_length=350)),
                ('mainBody', models.TextField(blank=True)),
                ('bodyText', models.TextField(blank=True)),
                ('pattern', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=350)),
                ('advantage_1', models.TextField(blank=True)),
                ('advantage_2', models.TextField(blank=True)),
                ('reason_1', models.TextField(blank=True)),
                ('reason_2', models.TextField(blank=True)),
                ('reason_3', models.TextField(blank=True)),
                ('slogan', models.TextField(blank=True)),
                ('bodyPoint', models.CharField(blank=True, max_length=350)),
                ('bodyCopy', models.TextField(blank=True)),
            ],
        ),
    ]
