# Generated by Django 3.2.7 on 2022-05-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_articletemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletemplate',
            name='advantage_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articletemplate',
            name='templatedType',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
