# Generated by Django 3.2.7 on 2022-05-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220519_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletemplate',
            name='product_category',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
