# Generated by Django 3.2.7 on 2022-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_articletemplate_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='product_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
