# Generated by Django 3.2.7 on 2022-08-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220803_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastSubscribeDate',
            field=models.DateField(blank=True),
        ),
    ]
