# Generated by Django 3.2.7 on 2022-08-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_profile_lastsubscribedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastSubscribeDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
